FROM node:20-alpine AS build
WORKDIR /app
COPY package.json pnpm-lock.yaml ./
RUN corepack enable && pnpm i --frozen-lockfile
COPY . .
RUN pnpm build


FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
# (optional) add a default.conf to route / to index.html for SPA